name: darknorm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - opencv
  - pip=21.0.1
  - python=3.8
  - cudatoolkit=10.2
  - pytorch=1.12.1
  - torchvision=0.13.1
  - six
  - pip:
    - tensorboardx==2.3.0
    - protobuf==3.20
